"test push"

diff --git a/lbsh_installer b/lbsh_installer
--- a/lbsh_installer
+++ b/lbsh_installer
@@ -4,34 +4,49 @@ SCRIPT_VERSION="1.0.0"
 SCRIPT_NAME="lbsh_installer"
 
 function msg(){
-    if [ "$1" == "err" ]
+    if [ "$1" == "log" ]
     then
-        echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $2" 1>&2
-    elif [ "$1" == "info" ]
-    then
-        echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
+        if [ "$2" == "error" ]
+        then
+            echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $3" 1>&2
+        else
+        then
+            echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
+        fi
     else
-        echo "$*"
+    then
+        if [ "$1" == "error" ]
+        then
+            echo -e "\e[31mERROR\e $*"
+        else
+        then
+            echo "$*"
+        fi
     fi
 }
 
+msg "123"
+msg log "123"
+msg error "123"
+msg log error "123"
 
-if [ "$1" == "" ] || [ "$1" == "-h" ]
-then
-    msg "   Usage: $0 [options] [command]"
-    msg " "
-    msg "   Commands: "
-    msg "          lssh             Install global command lssh"
-    msg " "
-    msg "   Options: "
-    msg "          <default>,-h     Output usage information"
-    msg "          -v               Verbose mode"
-elif [ "$1" == "lssh" ]
-then
-    msg "lssh"
-elif [ "$1" == "-v" ]
-then
-    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
-else
-    msg ERROR "$1 is not supported by ${SCRIPT_NAME}"
-fi
+
+# if [ "$1" == "" ] || [ "$1" == "-h" ]
+# then
+#     msg "   Usage: $0 [options] [command]"
+#     msg " "
+#     msg "   Commands: "
+#     msg "          lssh             Install global command lssh"
+#     msg " "
+#     msg "   Options: "
+#     msg "          <default>,-h     Output usage information"
+#     msg "          -v               Verbose mode"
+# elif [ "$1" == "lssh" ]
+# then
+#     msg "lssh"
+# elif [ "$1" == "-v" ]
+# then
+#     msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
+# else
+#     msg "$1 is not supported by ${SCRIPT_NAME}"
+# fi
diff --git a/lssh/lssh b/lssh/lssh
--- a/lssh/lssh
+++ b/lssh/lssh
@@ -5,14 +5,24 @@ SCRIPT_VERSION="1.0.0"
 SCRIPT_NAME="lb-ssh"
 
 function msg(){
-    if [ "$1" == "err" ]
+    if [ "$1" == "log" ]
     then
-        echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $2" 1>&2
-    elif [ "$1" == "info" ]
-    then
-        echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
+        if [ "$2" == "error" ]
+        then
+            echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $3" 1>&2
+        else
+        then
+            echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
+        fi
     else
-        echo "$*"
+    then
+        if [ "$1" == "error" ]
+        then
+            echo -e "\e[31mERROR\e $*"
+        else
+        then
+            echo "$*"
+        fi
     fi
 }
 
