change construction

diff --git a/lbsh_installer/lbsh_installer b/lbsh_installer/lbsh_installer
--- a/lbsh_installer/lbsh_installer
+++ b/lbsh_installer/lbsh_installer
@@ -1,187 +1,370 @@
 #!/bin/bash
-# TODO 重新梳理安装目录
-#命令安装器
-SCRIPT_VERSION="2.0.0"
-SCRIPT_NAME="lbsh_installer"
-BANNER_COLOR="blue"
-LBSH_HOME="$HOME/.lbsh"
-LBSH_CONFIG_HOME="$LBSH_HOME/config"
-LBSH_LIB_HOME="$LBSH_HOME/lib"
-LBSH_CACHE_HOME="$LBSH_HOME/cache"
-LBSH_LOG_HOME="$LBSH_HOME/log"
+VERSION="3.0.0"
+# 交互方式
+# 1 非交互式 passive
+# 2 交互式 interactive
+INTERVIEW_MODE=1
+FINISH_TIPS=()
 
-INSTALL_SUPPORT_ARR=("lssh" "tester")
-INSTALL_TO_BIN_HOME="/usr/bin"
+# tools
+# 以下都是工具方法
+function cecho() {
+    if [ "$1" == "red" ]; then
+        echo -e "\033[31m$2\033[0m"
+    elif [ "$1" == "yellow" ]; then
+        echo -e "\033[33m$2\033[0m"
+    elif [ "$1" == "green" ]; then
+        echo -e "\033[32m$2\033[0m"
+    fi
+}
 
-LSSH_INSTALL_HOME="./lssh"
-LSSH_LIB_HOME="$LBSH_LIB_HOME/lssh"
-LSSH_INSTALL_LIB_HOME="$LSSH_INSTALL_HOME/lib"
-LSSH_INSTALL_LIB_ARR=("remote.py")
-LSSH_CONFIG_HOME="$LBSH_CONFIG_HOME/lssh"
-LSSH_CONFIG_REMOTE_LIST="remote_list.config"
-LSSH_SHELL="lssh"
+function banner() {
+    cecho red ""
+    cecho red ""
+    cecho red " ██▓     █    ██  ▒█████   ▄▄▄▄    ▒█████       ██████  ██░ ██ ▓█████  ██▓     ██▓    "
+    cecho red "▓██▒     ██  ▓██▒▒██▒  ██▒▓█████▄ ▒██▒  ██▒   ▒██    ▒ ▓██░ ██▒▓█   ▀ ▓██▒    ▓██▒    "
+    cecho red "▒██░    ▓██  ▒██░▒██░  ██▒▒██▒ ▄██▒██░  ██▒   ░ ▓██▄   ▒██▀▀██░▒███   ▒██░    ▒██░    "
+    cecho red "▒██░    ▓▓█  ░██░▒██   ██░▒██░█▀  ▒██   ██░     ▒   ██▒░▓█ ░██ ▒▓█  ▄ ▒██░    ▒██░    "
+    cecho red "░██████▒▒▒█████▓ ░ ████▓▒░░▓█  ▀█▓░ ████▓▒░   ▒██████▒▒░▓█▒░██▓░▒████▒░██████▒░██████▒"
+    cecho red "░ ▒░▓  ░░▒▓▒ ▒ ▒ ░ ▒░▒░▒░ ░▒▓███▀▒░ ▒░▒░▒░    ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒░░ ▒░ ░░ ▒░▓  ░░ ▒░▓  ░"
+    cecho red "░ ░ ▒  ░░░▒░ ░ ░   ░ ▒ ▒░ ▒░▒   ░   ░ ▒ ▒░    ░ ░▒  ░ ░ ▒ ░▒░ ░ ░ ░  ░░ ░ ▒  ░░ ░ ▒  ░"
+    cecho red "  ░ ░    ░░░ ░ ░ ░ ░ ░ ▒   ░    ░ ░ ░ ░ ▒     ░  ░  ░   ░  ░░ ░   ░     ░ ░     ░ ░   "
+    cecho red "    ░  ░   ░         ░ ░   ░          ░ ░           ░   ░  ░  ░   ░  ░    ░  ░    ░  ░"
+    cecho red "                                ░                                                     "
+    cecho red ""
+}
 
-# 消息输出统一
-function msg() {
-    if [ "$1" == "log" ]; then
-        if [ "$2" == "error" ]; then
-            echo -e "[${SCRIPT_NAME}] $(date '+%Y-%m-%d %H:%M:%S') \e[31mERROR\e[0m: $3" 1>&2
-        else
-            echo -e "[${SCRIPT_NAME}] $(date '+%Y-%m-%d %H:%M:%S')  INFO: $2"
-        fi
+function title() {
+    if [[ "${1}" == "npd" ]]; then
+        echo -e "\033[1m${2}\033[0m"
     else
-        if [ "$1" == "error" ]; then
-            echo -e "\e[31mERROR:\e[0m $2"
-        else
-            echo -e "$*"
-        fi
+        echo
+        echo
+        echo -e "\033[1m${1}\033[0m"
+        echo
     fi
 }
 
-function bannerColor() {
-    case ${2} in
-        black) color=0
-        ;;
-        red) color=1
-        ;;
-        green) color=2
-        ;;
-        yellow) color=3
-        ;;
-        blue) color=4
-        ;;
-        magenta) color=5
-        ;;
-        cyan) color=6
-        ;;
-        white) color=7
-        ;;
-        *) echo "color is not set"; exit 1
-        ;;
-    esac
-
-    local msg="${3} ${1} ${3}"
-    local edge
-    edge=${msg//?/$3}
-    tput setaf ${color}
-    tput bold
-    msg
-    msg "${edge}"
-    msg "${msg}"
-    msg "${edge}"
-    tput sgr 0
-    msg
+function load_print() {
+    load_array=("⠇" "⠋" "⠙" "⠸" "⠴" "⠦")
+    load_index=$1
+    let array_index=load_index%${#load_array[*]}
+    printf "\r\033[?25l\033[32m${load_array[$array_index]}\033[0m %s" "$2"
 }
 
-function mkIfNotExistDir() {
-    if [ $1 != "" ]; then
-        if [ ! -d "$1" ]; then
-            if [ "$2" == "print" ]; then
-                msg "$1 is not exist,creating now."
-            fi
-            mkdir $1
-        else
-            if [ "$2" == "print" ]; then
-                msg "$1 is already exist."
-            fi
-        fi
+function load_success() {
+    # 判断终端宽度
+    sp=$(stty size | awk '{print $1}')
+    # 判断输出宽度
+    out_len=$(echo ${1} | wc -L)
+    # 计算所需填充量
+    let sp=sp-out_len-3
+    printf "\r\033[?25l\033[32m√\033[0m %s%-${sp}s\33[?25h\n" "$1"
+}
+
+function load_error() {
+    # 判断终端宽度
+    sp=$(stty size | awk '{print $1}')
+    # 判断输出宽度
+    out_len=$(echo ${1} | wc -L)
+    # 计算所需填充量
+    let sp=sp-out_len-3
+    printf "\r\033[?25l\033[31mx\033[0m %s%-${sp}s\33[?25h\n" "$1"
+}
+
+function pause() {
+    # 非交互模式直接退出
+    # TODO 为了输出一个\n(为了好看:( )多执行了一个判断  挂个todo学习后再来看看有没有别的解决方案
+    [ ${INTERVIEW_MODE} == 2 ] || echo && [ ${INTERVIEW_MODE} == 2 ] || exit 1
+    echo
+    if [ "${1}" == "exit" ]; then
+        echo "Installer has been terminated, press any to exit..."
+        sed -n q </dev/tty
+        exit 1
+    elif [ "$1" == "finish" ]; then
+        echo "Installer has been completed, press any to exit..."
+        sed -n q </dev/tty
+        exit 1
+
+    else
+        echo "Press enter to continue...(Ctrl+C to exit)"
+        sed -n q </dev/tty
     fi
 }
 
-function tcIfNotExistDir() {
-    if [ $1 != "" ]; then
-        if [ ! -f "$1" ]; then
-            if [ "$2" == "print" ]; then
-                msg "$1 is not exist,creating now."
-            fi
-            touch $1
-        else
-            if [ "$2" == "print" ]; then
-                msg "$1 is already exist."
-            fi
-        fi
+function checkCmdIsExist() {
+    exist=$(command -v $1)
+    if [ -n "${exist}" ]; then
+        return 0
+    else
+        return 1
     fi
 }
 
-function readForTimes(){
+# 输入判断用户确认
+# $1 read tips
+# $2 retry times default for 3
+function readForTimes() {
     times=3
     if [ "$1" != "" ]; then
         if [ "$2" != "" ]; then
             let times=$2
         fi
         while [ $times -gt 0 ]; do
-            read -p "$1" inputArg
+            read -p "${1}[yY/nN]: " -N 1 rc
+            inputArg=$rc
+            # 输入是回车则format成Y
+            if [[ $rc == $'\x0a' ]]; then
+                inputArg="y"
+            else
+                echo
+            fi
             case $inputArg in
-                [yY]*)
+            [yY]*)
                 let times=0
                 ;;
-                [nN]*)
-                    lbshBanne quit
-                    exit
+            [nN]*)
+                echo
+                exit 1
                 ;;
-                *)
-                    if [ $times -eq 1 ]; then
-                        msg "run out of retry, exit."
-                        lbshBanne quit
-                        exit
-                    else
-                        let times--
-                        msg "just enter y or n, please enter again, $times more times retry."
-                    fi
+            *)
+                if [ $times -eq 1 ]; then
+                    cecho red "run out of retry, exit."
+                    exit
+                else
+                    let times--
+                    cecho red "just enter y or n, please enter again, $times more times retry."
+                fi
                 ;;
             esac
         done
     fi
 }
 
-function lbshBanne(){
-    if [ "$1" == "welcome" ]; then
-        bannerColor "welcome to $SCRIPT_NAME(v$SCRIPT_VERSION)!" $BANNER_COLOR "*"         
-    elif [ "$1" == "quit" ]; then
-        bannerColor "thanks for using $SCRIPT_NAME(v$SCRIPT_VERSION)." $BANNER_COLOR "*" 
-    fi    
+# logic
+# 以下都是安装器逻辑层面方法
+function welcome() {
+    banner
+    title npd "Welcome to the intaller for lbsh! (${VERSION})"
 }
-
-function lbshHomeCheck() {
-    msg ">>check for lbshHome($LBSH_HOME)"
-    mkIfNotExistDir $LBSH_HOME print
-    mkIfNotExistDir $LBSH_CONFIG_HOME print
-    mkIfNotExistDir $LBSH_LIB_HOME print
-    mkIfNotExistDir $LBSH_CACHE_HOME print
-    mkIfNotExistDir $LBSH_LOG_HOME print
-    msg "\n"
+# 安装器本身需要的环境检查安装
+function env_check() {
+    env_cmd_check
+    env_dir_check
+    env_script_check
+    env_variable_check
+    echo
+    cecho green "Environment check finish, Your environment is intact..."
 }
-
-function installerForLssh() {
-   msg "lssh"
-}
-
-if [ "$1" == "" ] || [ "$1" == "-h" ]; then
-    msg "   Usage: $0 [options] [command]"
-    msg " "
-    msg "   Commands: "
-    msg "          ps,ls,list       Check luobo tools list"
-    msg "          i,install        Install luobo tools in your system"
-    msg "          u,unstall        Unstall luobo tools"
-    msg "          clear            Clear lbsh home"
-    msg " "
-    msg "   Options: "
-    msg "          <default>,-h     Output usage information"
-    msg "          -v               Verbose mode"
-elif [ "$1" == "ps" ] || [ "$1" == "ls" ] || [ "$1" == "list" ]; then
-    
-elif [ "$1" == "i" ]; then
-    lbshBanne welcome
-    if [ "$2" == "" ]; then
-        msg "Unable to install empty, plase try to install [${INSTALL_SUPPORT_ARR[*]}]."
-    elif [ "$2" == "lssh" ]; then
-        installerForLssh
-    else
-        msg "$2 is not supported for installation, plase try to install [${INSTALL_SUPPORT_ARR[*]}]."
+# 检查所需系统命令环境，不存在则退出
+function env_cmd_check() {
+    cmd_array=("node")
+    if ((${#cmd_array[*]} > 0)); then
+        title "Installation Commands Environment Check:"
+        error_env=""
+        for cmd_env in ${cmd_array[@]}; do
+            if checkCmdIsExist ${cmd_env}; then
+                load_success "${cmd_env}"
+            else
+                load_error "${cmd_env}"
+                error_env="${error_env}${cmd_env} "
+            fi
+        done
+        echo
+        # 环境缺失
+        if [ -n "$error_env" ]; then
+            cecho red "Required environment was not found...(${error_env})"
+            pause exit
+        fi
+        # 环境完整
+        cecho green "Congratulations!!You have everything installer need!!"
     fi
-    lbshBanne quit
-elif [ "$1" == "-v" ]; then
-    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
-else
-    msg "$1 is not supported by ${SCRIPT_NAME}."
-fi
+}
+# 检查本地已安装环境目录，不存在则提示创建
+function env_dir_check() {
+    dir_array=("${HOME}/.lbsh" "${HOME}/.lbsh/bin" "${HOME}/.lbsh/lib")
+    if ((${#dir_array[*]} > 0)); then
+        title "Installation Home Check:"
+        for dir in ${dir_array[@]}; do
+            if [ -d $dir ]; then
+                load_success "${dir}"
+            else
+                load_error "${dir}"
+                readForTimes "Required folder(${dir}) does not exist,Confirm to create"
+                mkdir -p ${dir}
+                load_success "${dir} comfirm create"
+            fi
+        done
+    fi
+}
+# 检查所需脚本，不存在则提示下载，错误则退出
+# 暂行 安装的所有脚本必须版本跟安装脚本同步
+# TODO 后续更新更新检查方案来分别指定最高版本
+function env_script_check() {
+    script_array=("/home/luobo/.lbsh/.lbsh_profile")
+    script_upgrade_array=(
+        "cp -f ./libs/lbsh_profile ${script_array[0]}"
+    )
+    script_upgrade_init_array=(
+        "source ${script_array[0]}"
+    )
+    script_upgrade_tips_array=(
+        "environment file has been change, please add lb_profile($HOME/.lbsh/.lbsh_profile) into your environment(suggestion: [ ! -f \"$HOME/.lbsh/.lbsh_profile\" ] || source $HOME/.lbsh/.lbsh_profile) and resource"
+    )
+    if ((${#script_array[*]} > 0)); then
+        title "Installation Script Check:"
+        for ((i = 0; i < ${#script_array[*]}; i++)); do
+            script=${script_array[$i]}
+            version=$(${script} -v 2>/dev/null)
+            # 版本号包含母版本
+            if [[ "${version}" == *"${VERSION}"* ]]; then
+                load_success "${script}(${version})"
+            else
+                # 需求脚本不存在
+                load_error "${script}(${version})"
+                readForTimes "Required script(${script}) does not exist,Confirm to upgrade"
+                # 执行更新安装脚本
+                script_upgrade=${script_upgrade_array[$i]}
+                ${script_upgrade}
+                # 判断更新安装脚本执行结果
+                if [ $? -eq 0 ]; then
+                    # 检查是否有更新后初始化选项脚本，有就执行
+                    script_upgrade_init=
+                    [[ ! -n "${script_upgrade_init_array[$i]}" ]] || ${script_upgrade_init}
+                    load_success "${script} upgrade success ($(${script} -v 2>/dev/null))"
+                    [[ ! -n "${script_upgrade_tips_array[$i]}" ]] || FINISH_TIPS[${#FINISH_TIPS[*]}]="${script_upgrade_tips_array[$i]}"
+                else
+                    cecho red "${script}(${version}) upgrade error"
+                    pause exit
+                fi
+            fi
+        done
+    fi
+}
+
+# 环境变量检查，静默检查安装完成后提示安装环境变量
+function env_variable_check() {
+    var_array=("LBSH_HOME")
+    if ((${#var_array[*]} > 0)); then
+        var_error=()
+        for var in ${var_array[@]}; do
+            var_content=$(eval echo '$'${var})
+            [[ -n "${var_content}" ]] || var_error[${#var_error[*]}]=${var}
+        done
+        ((${#var_error[*]} <= 0)) || FINISH_TIPS[${#FINISH_TIPS[*]}]="lbsh environment variable missing, please check your environment file or resource your environment...(missing items: ${var_error})"
+    fi
+}
+
+# 交互式的支持的命令菜单选择
+function lbsh_list() {
+    lbsh_array=("lssh" "lgh")
+    if ((${#lbsh_array[*]} > 0)); then
+        title "Luobo Shell List:"
+        for ((i = 0; i < ${#lbsh_array[*]}; i++)); do
+            let index=i+1
+            echo "${index}) ${lbsh_array[i]}"
+        done
+        echo
+        times=3
+        while [ $times -gt 0 ]; do
+            read -p "Enter the serial number to choose one(1-${#lbsh_array[*]}): " -N 1 rc
+            echo
+            times_m=0
+            expr $rc + 0 &>/dev/null && {
+                let index=rc-1
+                inputArg=${lbsh_array[index]}
+                [[ ${lbsh_array[@]/${inputArg}/} != ${lbsh_array[@]} ]] && {
+                    let times=0
+                    echo "Yes ${inputArg}"
+                } || {
+                    times_m=1
+                }
+            } || {
+                times_m=1
+            }
+            (($times_m == 1)) && {
+                if [ $times -eq 1 ]; then
+                    cecho red "run out of retry, exit."
+                    echo
+                    exit
+                else
+                    let times--
+                    cecho red "Input error, Select the one you want to install, please enter again, $times more times retry."
+                fi
+            }
+        done
+    else
+        echo
+        cecho red "There are no commands to install..."
+        pause exit
+    fi
+}
+
+# 安装结束
+function install_finsh() {
+    echo
+    finsh_echo="Congratulations! Install Success!"
+    cecho green "${finsh_echo}"
+    # cecho green "Congratulations! Install Success! Please souce your environment before using...(# source /etc/profile or your sh...)"
+    if ((${#FINISH_TIPS[*]} > 0)); then
+        echo
+        finsh_echo="matters need attention:\n"
+        finsh_echo="${finsh_echo}=================================================================================\n"
+        for ((i = 0; i < ${#FINISH_TIPS[*]}; i++)); do
+            ((${i} == 0)) || finsh_echo="${finsh_echo}\n"
+            let index=i+1
+            finsh_echo="${finsh_echo}${index}. ${FINISH_TIPS[$i]}"
+        done
+        finsh_echo="${finsh_echo}\n================================================================================="
+        cecho yellow "${finsh_echo}"
+    fi
+}
+
+# 非交互式安装模式检查，检查到合法条件则不进入交互窗口
+function check_passive_mode() {
+    if [ "$1" == "-h" ]; then
+        welcome
+        echo
+        echo "Usage: $0 [options] [command] to passive mode or "
+        echo "       $0 to interactive mode"
+        echo
+        echo "Commands: "
+        echo "       ps,ls,list       Check luobo tools list"
+        echo "       i,install        Install luobo tools in your system"
+        echo "       u,unstall        Unstall luobo tools"
+        echo "       clear            Clear lbsh home"
+        echo
+        echo "Options: "
+        echo "       -h,-help         Output usage information"
+        echo "       -v               Verbose mode"
+        echo
+        return 0
+    elif [ "$1" == "ps" ] || [ "$1" == "ls" ] || [ "$1" == "list" ]; then
+        echo ls
+        return 0
+    elif [ "$1" == "i" ] || [ "$1" == "install" ]; then
+        welcome
+        env_check
+        echo "install $2"
+        return 0
+    elif [ "$1" == "-v" ]; then
+        echo "${VERSION}"
+        return 0
+    else
+        return 1
+    fi
+}
+
+function main() {
+    check_passive_mode $* && exit 1 || {
+        let INTERVIEW_MODE=2
+        clear
+        welcome
+        env_check
+        lbsh_list
+        install_finsh
+        pause finish
+    }
+}
+
+main $*
