rebuilding

diff --git a/lbsh_installer/test b/lbsh_installer/test
--- a/lbsh_installer/test
+++ b/lbsh_installer/test
@@ -1,6 +1,10 @@
 #!/bin/bash
-ips=("11" "22")
-i=0
-for((i=0;i<${#ips[*]};i++)); do
-    echo ${ips[$i]}
-done
+a="igconfig 2>/dev/null"
+${a}
+echo $?
+# if [ $? -eq 0 ]
+# then
+#     echo "succeed"
+# else
+#     echo "failed"
+# fi
